# Generated by Django 5.1.2 on 2024-10-21 07:50

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('img_path', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_description', models.CharField(max_length=255, null=True)),
                ('organic', models.BooleanField(default=False)),
                ('fresh', models.BooleanField(default=False)),
                ('sales', models.BooleanField(default=False)),
                ('discount', models.BooleanField(default=False)),
                ('Expired', models.BooleanField(default=False)),
                ('popularity', models.BooleanField(null=True)),
                ('fantastic', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(related_name='products', to='store.category')),
            ],
        ),
    ]
