# Generated by Django 5.1.2 on 2024-10-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Expired',
            new_name='expired',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fantastic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='popularity',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
