# Generated by Django 5.1.2 on 2024-10-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_expired_product_expired_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='img_path',
            field=models.CharField(default='df_image.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
