# Generated by Django 5.1.1 on 2024-10-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='expired',
            new_name='for_orchestra',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='fresh',
            new_name='for_piano',
        ),
        migrations.RemoveField(
            model_name='product',
            name='organic',
        ),
    ]
