# Generated by Django 5.1.1 on 2024-10-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_expired_product_for_orchestra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='df_image.png', max_length=255, upload_to='static/img/', verbose_name='image'),
        ),
    ]
