# Generated by Django 5.1.2 on 2024-10-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='for_orchestra',
        ),
        migrations.RemoveField(
            model_name='product',
            name='for_piano',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales',
        ),
    ]
