# Generated by Django 5.1.2 on 2024-11-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='პროდუქტის აღწერა'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description_ka',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='პროდუქტის აღწერა'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='სახელი'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ka',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='სახელი'),
        ),
    ]
